name: Response Time CI
on:
  repository_dispatch:
    types: [response_time]
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Check response time
    runs-on: ubuntu-latest
    steps:
      - name: Check response time
        uses: upptime/uptime-monitor@v1
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
