name: Setup CI
on:
  push:
    branches:
      - master
      - main
    paths:
      - .upptimerc.yml
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup
        uses: upptime/uptime-monitor@v1.41.3
        with:
          command: "setup"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
